Algoritmo "semnome"

Var

user, passowrd:  caractere
      
   Inicio
   escreva("digite seu usuário")
   leia(user)
   escreva("digite sua senha")
   leia(passowrd)
   
   enquanto (user <> "admin") ou (passowrd <> "admin") faca
   escreval("usuário ou senha inválidos")
   leia(user)
   escreva("digite seu usuário")
   leia(user)
   escreva("digite sua senha")
   leia(passowrd)
   fimenquanto

 escreval("seja bem vindo ao sistema")
Fimalgoritmo
